In [4]:
import pyaudio
import os
import struct
import numpy as np
import matplotlib.pyplot as plt
import time
from tkinter import TclError

# to display the output in a window outside the jupyter notebook
%matplotlib tk

# constants
CHUNK = 1024 * 2             # samples per frame
FORMAT = pyaudio.paInt16     # audio format (bytes per sample?)
CHANNELS = 1                 # single channel for microphone
RATE = 44100                 # samples per second

In [5]:
# create matplotlib figure and axes
fig, ax = plt.subplots(1, figsize=(15, 7))

p = pyaudio.PyAudio()
stream = p.open(
    format=FORMAT,
    channels=CHANNELS,
    rate=RATE,
    input=True,
    output=True,
    frames_per_buffer=CHUNK
)

# variable for plotting
x_n = np.arange(0, 2 * CHUNK, 2)

# create a line object with random data
line, = ax.plot(x_n, np.random.rand(CHUNK), '-', lw=2)

# basic formatting for the axes
ax.set_title('AUDIO WAVEFORM')
ax.set_xlabel('samples')
ax.set_ylabel('volume')
ax.set_ylim(0, 255)
ax.set_xlim(0, 2 * CHUNK)
plt.setp(ax, xticks=[0, CHUNK, 2 * CHUNK], yticks=[0, 128, 255])

# show the plot
plt.show(block=False)

print('stream started')

# for measuring frame rate
frame_count = 0
start_time = time.time()

while True:
    
    # binary data
    data = stream.read(CHUNK)  
    
    # convert data to integers, make np array, then offset it by 127
    data_int = struct.unpack(str(2 * CHUNK) + 'B', data)
    
    # create np array and offset by 128
    data_np = np.array(data_int, dtype='b')[::2] + 128
    print(data_np)
    
    line.set_ydata(data_np)
    
    # update figure canvas
    try:
        fig.canvas.draw()
        fig.canvas.flush_events()
        frame_count += 1
        
    except TclError:
        
        # calculate average frame rate
        frame_rate = frame_count / (time.time() - start_time)
        
        print('stream stopped')
        print('average frame rate = {:.0f} FPS'.format(frame_rate))
        break

stream started
[143 110 177 ...  62 201  68]
[105 207  90 ... 181  68 211]
[ 72  62 183 ...  96  19 147]
[149  10  23 ...  86  39  44]
[189  71  90 ... 152 128 200]
[ 24 253 235 ...  56 169  90]
[160 246 247 ... 108 209 223]
[144 205  22 ... 252 190 152]
[182 158  85 ... 186  87  49]
[ 56 106 250 ...  88  80 138]
[ 52 233 216 ... 194  89  76]
[ 66 148 124 ...   0 155 214]
[170 189 155 ...  27   7 248]
[ 38  34 219 ... 148 249 168]
[121 149  62 ... 203 113  58]
[131 203 239 ... 217   8 173]
[251 227 221 ... 217 125  61]
[ 57 199 156 ... 193 132 152]
[ 36 211 136 ...  49  85 216]
[ 44 204  45 ... 206  91 206]
[ 50 252 212 ... 221 229  25]
[129   0  39 ...  83 212 201]
[224 227 112 ...  41 227 242]
[ 44 241  73 ...  94 152 189]
[172 255 148 ...  62  27 136]
[136  86 251 ... 214  75 179]
[172 245  79 ... 154 252 110]
[254  42 191 ... 167  93  58]
[131 107   6 ...  90 243 209]
[185 241  28 ... 201  12  44]
[  7  19 122 ...  85 119 150]
[216 109 103 ... 137  59 244]
[228 135  77 ...  18  43 

[135  14 176 ... 254  80 164]
[196 134  10 ...  30 174 119]
stream stopped
average frame rate = 14 FPS
